### ISSUE TITLE
using gulp

### ISSUE THREAD

**Issue by eddietohier** [justim/postcss-svg-fallback#23]
need your help please.... I`m new to postcss, is there any tutorial implement svg-fallback with gulp?

**Comment by justim** [comment]
[`postcss-svg-fallback`](https://github.com/justim/postcss-svg-fallback) is a plugin for [PostCSS](https://github.com/postcss/postcss). You would need a Gulp plugin for PostCSS and add this plugin to your config: https://github.com/postcss/gulp-postcss#passing-plugins-directly

Something like this:

```js
const gulp = require('gulp');
const postcss = require('gulp-postcss');
const svgFallback = require('postcss-svg-fallback')

gulp.task('css', function() {
    const plugins = [
        svgFallback({ /* options for svg fallback, see README */ }),
    ];

    return gulp.src('./src/*.css')
        .pipe(postcss(plugins))
        .pipe(gulp.dest('./dest'));
});
```

**Comment by eddietohier** [comment]
Hi Tim.. thanks for your reply but i got this error:

Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but postcss-svg-fallback uses 5.2.18. Perhaps this is the source of the error below.

events.js:173
      throw er; // Unhandled 'error' event
      ^
TypeError: css.eachRule is not a function
    at /Users/eddie/Desktop/gulp-playground/node_modules/postcss-svg-fallback/index.js:34:7
    at LazyResult.run (/Users/eddie/Desktop/gulp-playground/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.asyncTick (/Users/eddie/Desktop/gulp-playground/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:192:32)
    at /Users/eddie/Desktop/gulp-playground/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:197:27
Emitted 'error' event at:
    at Transform.onerror (/Users/eddie/Desktop/gulp-playground/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Transform.emit (events.js:197:13)
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at Transform.afterTransform (_stream_transform.js:94:3)
    at Immediate.<anonymous> (/Users/eddie/Desktop/gulp-playground/node_modules/gulp-postcss/index.js:93:9)
    at processImmediate (timers.js:637:19)

**Comment by eddietohier** [comment]
here my gulp file:

gulp.task('styles', function() {
    var plugin = [
        lost(),
        postcssSVG(),
        svgFallback(),
        autoprefixer({browsers:['last 2 version']})
    ];
    return gulp.src('sources/stylus/**/!(_)*.styl')
        .pipe(stylus())
        .pipe(postcss(plugin))
        .pipe(gulp.dest('public/css/'));
});

**Comment by justim** [comment]
The plugin API changed in PostCSS `>=6`, would have to investigate for a bit, but that will be sometime after the weekend.

I'll keep you posted.

**Comment by eddietohier** [comment]
sure.. thanks

**Comment by justim** [comment]
Just pushed a new release to npm with a fix.

**Comment by eddietohier** [comment]
Awesome.. it's working with latest version PostCSS, Thanks a million tim

**Comment by justim** [comment]
You're welcome, have fun with it! 👍
